language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - master
  - nightly

matrix:
  allow_failures:
    - php:
        - master
        - nightly

install:
  - composer install

script:
  - composer test-coverage

after_script:
  - php vendor/bin/coveralls -v
